// This file is auto-generated by mobile/tool/generate_rust_payload.dart
// Do not edit manually.

#![allow(dead_code)]

#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct SnifferPayload {
    pub senderMac: [u8; 6],
    pub receiverMac: [u8; 6],
    pub rssi: i8,
}

