// ignore_for_file: avoid_print

import 'dart:io';

void main() {
  final payloadFile = File('lib/payload.dart');
  if (!payloadFile.existsSync()) {
    print('Error: lib/payload.dart not found.');
    exit(1);
  }

  final content = payloadFile.readAsStringSync();

  // Regex to find class name
  final classRegex = RegExp(r'class\s+(\w+)');
  final classMatch = classRegex.firstMatch(content);
  if (classMatch == null) {
    print('Error: Could not find class name in lib/payload.dart');
    exit(1);
  }
  final className = classMatch.group(1)!;

  // Regex to find fields with @type comments
  // Matches: // @type: [u8; 6]
  //          final Uint8List mac;
  final fieldRegex = RegExp(
    r'\/\/\s*@type:\s*([^\r\n]+)\r?\n\s*final\s+\w+\s+(\w+);',
    multiLine: true,
  );

  final fields = <Map<String, String>>[];
  for (final match in fieldRegex.allMatches(content)) {
    final rustType = match.group(1)!.trim();
    final fieldName = match.group(2)!.trim();
    fields.add({'name': fieldName, 'type': rustType});
  }

  if (fields.isEmpty) {
    print('Error: No fields annotated with @type found in lib/payload.dart');
    exit(1);
  }

  // Generate Rust code
  final buffer = StringBuffer();
  buffer.writeln(
    '// This file is auto-generated by mobile/tool/generate_rust_payload.dart',
  );
  buffer.writeln('// Do not edit manually.');
  buffer.writeln();
  buffer.writeln('#![allow(dead_code)]');
  buffer.writeln();
  buffer.writeln('#[repr(C, packed)]');
  buffer.writeln('#[derive(Debug, Copy, Clone)]');
  buffer.writeln('pub struct $className {');
  for (final field in fields) {
    buffer.writeln('    pub ${field['name']}: ${field['type']},');
  }
  buffer.writeln('}');
  buffer.writeln();

  // Write to firmware/src/payload.rs
  final outputFile = File('../firmware/src/payload.rs');
  outputFile.writeAsStringSync(buffer.toString());
  print('Successfully generated ${outputFile.path} from lib/payload.dart');
}
