#let glossary-entries = (
  (
    key: "IT",
    short: "IT",
    long: "Informatik",
    description: [Informatik],
    group: "acronyms",
  ),
  (
    key: "KI",
    short: "KI",
    long: "Künstliche Intelligenz",
    description: [Künstliche Intelligenz],
    group: "acronyms",
  ),
  (
    key: "WLAN",
    short: "WLAN",
    long: "Wireless Local Area Network",
    description: [Drahtloses lokales Netzwerk zur kabellosen Datenübertragung.],
    group: "acronyms",
  ),
  (
    key: "ESP32",
    short: "ESP32",
    long: "ESP32-Mikrocontroller",
    description: [Eine Familie von kostengünstigen und stromsparenden System-on-Chip-Mikrocontrollern mit integriertem WLAN und Bluetooth.],
    group: "acronyms",
  ),
  (
    key: "RSSI",
    short: "RSSI",
    long: "Received Signal Strength Indicator",
    description: [Indikator für die Empfangsfeldstärke kabelloser Kommunikationsnetze.],
    group: "acronyms",
  ),
  (
    key: "MAC",
    short: "MAC",
    long: "Media Access Control",
    description: [Die physische Adresse eines Netzwerkadapters zur Identifikation in einem Netzwerk.],
    group: "acronyms",
  ),
  (
    key: "IoT",
    short: "IoT",
    long: "Internet of Things",
    description: [Internet der Dinge – die Vernetzung physischer Objekte mit dem Internet.],
    group: "acronyms",
  ),
  (
    key: "UI",
    short: "UI",
    long: "User Interface",
    description: [Benutzeroberfläche zur Interaktion zwischen Mensch und Maschine.],
    group: "acronyms",
  ),
  (
    key: "NPU",
    short: "NPU",
    long: "Neural Processing Unit",
    description: [Spezialisierter Hardware-Prozessor zur effizienten Beschleunigung von künstlichen neuronalen Netzen und Machine-Learning-Algorithmen.],
    group: "acronyms",
  ),
  (
    key: "BLE",
    short: "BLE",
    long: "Bluetooth Low Energy",
    description: [Ein stromsparender Funkstandard zur kabellosen Datenübertragung im 2,4-GHz-Frequenzband.],
    group: "acronyms",
  ),
  (
    key: "OUI",
    short: "OUI",
    long: "Organizationally Unique Identifier",
    description: [Ein 24-Bit-Herstellercode im ersten 3-Byte-Block einer MAC-Adresse zur Identifikation des Hardwareherstellers.],
    group: "acronyms",
  ),
  (
    key: "SoC",
    short: "SoC",
    long: "System-on-Chip",
    description: [Ein integrierter Schaltkreis, der alle wesentlichen Komponenten eines Computersystems auf einem einzigen Chip vereint.],
    group: "acronyms",
  ),
  (
    key: "PCB",
    short: "PCB",
    long: "Printed Circuit Board",
    description: [Eine gedruckte Schaltung beziehungsweise Leiterplatte zur mechanischen Befestigung und elektrischen Verbindung elektronischer Bauteile.],
    group: "acronyms",
  ),
  (
    key: "UWB",
    short: "UWB",
    long: "Ultra-Wideband",
    description: [Eine Nahbereichs-Funktechnik zur hochpräzisen Entfernungs- und Positionsbestimmung.],
    group: "acronyms",
  ),
  (
    key: "PRISMA",
    short: "PRISMA",
    long: "Preferred Reporting Items for Systematic Reviews and Meta-Analyses",
    description: [Evidenzbasierte Mindeststandards für die Berichterstattung in systematischen Übersichtsarbeiten.],
    group: "acronyms",
  ),
  (
    key: "DFS",
    short: "DFS",
    long: "Dynamic Frequency Selection",
    description: [Verfahren zur automatischen Frequenzwahl im 5-GHz-WLAN-Band zur Vermeidung von Störungen priorisierter Radarsysteme.],
    group: "acronyms",
  ),
  (
    key: "CPU",
    short: "CPU",
    long: "Central Processing Unit",
    description: [Der zentrale Hauptprozessor eines Computersystems zur Befehlsverarbeitung.],
    group: "acronyms",
  ),
  (
    key: "RAM",
    short: "RAM",
    long: "Random Access Memory",
    description: [Der flüchtige Arbeitsspeicher zur temporären Datenhaltung während des Betriebs.],
    group: "acronyms",
  ),
  (
    key: "UAA",
    short: "UAA",
    long: "Universally Administered Address",
    description: [Eine vom Hersteller weltweit eindeutig vergebene physische MAC-Adresse.],
    group: "acronyms",
  ),
  (
    key: "LAA",
    short: "LAA",
    long: "Locally Administered Address",
    description: [Eine lokal verwaltete, temporäre MAC-Adresse zur Verhinderung von Tracking.],
    group: "acronyms",
  ),
  (
    key: "MTU",
    short: "MTU",
    long: "Maximum Transmission Unit",
    description: [Die maximale Paketgröße eines Datenblocks auf der Netzwerkschicht.],
    group: "acronyms",
  ),
  (
    key: "SDK",
    short: "SDK",
    long: "Software Development Kit",
    description: [Eine Sammlung von Software-Werkzeugen und Programmierbibliotheken zur Anwendungsentwicklung.],
    group: "acronyms",
  ),
  (
    key: "IE",
    short: "IE",
    long: "Information Element",
    description: [Standardisierte Datenfelder in 802.11-Management-Rahmen zur Übertragung von Geräte- und Netzwerkparametern.],
    group: "acronyms",
  ),
  (
    key: "GATT",
    short: "GATT",
    long: "Generic Attribute Profile",
    description: [Ein BLE-Protokoll zur Strukturierung des Datenaustauschs über Services und Charakteristiken.],
    group: "acronyms",
  ),
  (
    key: "OTM",
    short: "OTM",
    long: "On-the-Move",
    description: [Mobiles Erfassungsszenario zur Signalerfassung während der Fortbewegung.],
    group: "acronyms",
  ),
  (
    key: "no_std",
    short: raw("#![no_std]"),
    description: [Rust-Attribut zur Entwicklung von Bare-Metal-Firmware ohne Einbindung der Rust-Standardbibliothek.],
    group: "acronyms",
  ),
  (
    key: "AP",
    short: "AP",
    long: "Access Point",
    description: [Zentraler Drahtlos-Knotenpunkt zur Anbindung von WLAN-Endgeräten an ein Netzwerk. Auch Router oder Hotspot genannt.],
    group: "acronyms",
  ),
)
